name: ChestShop
main: muqsit\chestshop\Loader
api: 3.11.1
version: 5.0.1
commands:
  chestshop:
    aliases: ["cs", "cshop"]
permissions:
  chestshop.command.add:
    default: op
  chestshop.command.remove:
    default: op
